// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperStatus.DataAccess.DatabaseContext;


#nullable disable

namespace SuperTalk.DataAccess.Migrations
{
    [DbContext(typeof(SuperStatusDb))]
    [Migration("20250801152808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperTalk.Entities.Data.AiResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiAnalysisType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiResponseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalysisEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AnalysisStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExtractedPageDataId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExtractedPageDataId");

                    b.ToTable("AiResponseDataSet");
                });

            modelBuilder.Entity("SuperTalk.Entities.Data.ExtractedFileData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalysisEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AnalysisStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExtractedFileDataSet");
                });

            modelBuilder.Entity("SuperTalk.Entities.Data.ExtractedPageData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AnalysisStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExtractedFileDataId")
                        .HasColumnType("uuid");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExtractedFileDataId");

                    b.ToTable("ExtractedPageDataSet");
                });

            modelBuilder.Entity("SuperTalk.Entities.Data.AiResponse", b =>
                {
                    b.HasOne("SuperTalk.Entities.Data.ExtractedPageData", "Page")
                        .WithMany("AiResponseSet")
                        .HasForeignKey("ExtractedPageDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SuperTalk.Entities.Data.ExtractedPageData", b =>
                {
                    b.HasOne("SuperTalk.Entities.Data.ExtractedFileData", "File")
                        .WithMany("Pages")
                        .HasForeignKey("ExtractedFileDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("SuperTalk.Entities.Data.ExtractedFileData", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("SuperTalk.Entities.Data.ExtractedPageData", b =>
                {
                    b.Navigation("AiResponseSet");
                });
#pragma warning restore 612, 618
        }
    }
}
