#!/usr/bin/env bash
#
# Start SuperStatus on this machine and make it reachable by IP on your LAN.
#
#   ./start.sh
#
# Auto-detects this host's IP, writes a .env with generated secrets, and brings
# the stack up. Then open http://<this-host-ip>:8080 from any machine on your
# network and create your admin account.
#
# Overrides:  HOST_IP=10.0.0.5 WEB_PORT=8080 IDENTITY_PORT=8081 ./start.sh
#
# This serves plain HTTP on your LAN — fine for a trusted network. To expose it
# on the internet, put it behind a TLS reverse proxy instead (docs/self-hosting.md).
set -euo pipefail
cd "$(dirname "$0")"

WEB_PORT="${WEB_PORT:-8080}"
IDENTITY_PORT="${IDENTITY_PORT:-8081}"

HOST_IP="${HOST_IP:-$(hostname -I 2>/dev/null | awk '{print $1}')}"
if [ -z "$HOST_IP" ]; then
  echo "Could not detect this host's IP. Re-run with: HOST_IP=<your-server-ip> ./start.sh" >&2
  exit 1
fi

gen_secret() { openssl rand -base64 24 2>/dev/null || head -c 18 /dev/urandom | base64; }

if [ ! -f .env ]; then
  echo "Writing .env for LAN access on ${HOST_IP} ..."
  # .env holds POSTGRES_PASSWORD / OIDC_WEB_CLIENT_SECRET — create it owner-only
  # (umask 077 → mode 0600) so other local users on the server can't read it.
  ( umask 077
    cat > .env <<EOF
# Generated by start.sh — SuperStatus reachable on the LAN by IP.
# Plain HTTP on the LAN. For internet exposure use a TLS proxy (docs/self-hosting.md).
BIND_ADDR=0.0.0.0
WEB_PORT=${WEB_PORT}
IDENTITY_PORT=${IDENTITY_PORT}
WEBAPP_HTTP=http://${HOST_IP}:${WEB_PORT}
IDP_PUBLIC_HTTP=http://${HOST_IP}:${IDENTITY_PORT}
IDP_HTTP=http://identity:8080
POSTGRES_PASSWORD=$(gen_secret)
OIDC_WEB_CLIENT_SECRET=$(gen_secret)
EOF
  )
  chmod 600 .env 2>/dev/null || true   # belt-and-suspenders if umask was overridden
else
  echo "Using existing .env (delete it to regenerate)."
fi

echo "Building and starting (first run takes a few minutes) ..."
docker compose up -d --build

cat <<EOF

SuperStatus is starting. From any machine on your network, open:

    http://${HOST_IP}:${WEB_PORT}

The first visit creates your administrator account.
Logs:  docker compose logs -f      Stop:  docker compose down
EOF
