#!/usr/bin/env bash
#
# Start SuperStatus on this machine and make it reachable by IP on your LAN.
#
#   ./start.sh
#
# Writes a .env with generated secrets and brings the stack up. Then open
# http://<this-host>:8080 from any machine on your network and create your admin
# account. The login (OIDC) redirect follows whatever host you open the app at —
# an IP, a hostname, localhost — so there's no host to configure and no wrong
# guess to strand the redirect (#358); the issuer is pinned to the internal
# authority. The browser must also reach the identity
# port (:8081) directly, so open BOTH ports in your firewall / cloud NSG.
#
# Overrides:  HOST_IP=10.0.0.5 WEB_PORT=8080 IDENTITY_PORT=8081 ./start.sh
# (HOST_IP only changes the URL printed at the end — it is not baked into anything.)
#
# This serves plain HTTP on your LAN — fine for a trusted network. To expose it
# on the internet, put it behind a TLS reverse proxy instead (docs/self-hosting.md).
set -euo pipefail
cd "$(dirname "$0")"

WEB_PORT="${WEB_PORT:-8080}"
IDENTITY_PORT="${IDENTITY_PORT:-8081}"

# #358: the OIDC login redirect now FOLLOWS whatever host you open the app at
# (an IP, a hostname, localhost) — nothing is baked into .env (the issuer is pinned
# to the internal authority) — so HOST_IP is only a display hint for the "open this
# URL" line printed at the end. A wrong guess no longer strands the login redirect.
# Override it just to change the hint.
HOST_IP="${HOST_IP:-$(hostname -I 2>/dev/null | awk '{print $1}')}"
[ -n "$HOST_IP" ] || HOST_IP="localhost"

gen_secret() { openssl rand -base64 24 2>/dev/null || head -c 18 /dev/urandom | base64; }

if [ ! -f .env ]; then
  echo "Writing .env for LAN access on ${HOST_IP} ..."
  # .env holds POSTGRES_PASSWORD / OIDC_WEB_CLIENT_SECRET — create it owner-only
  # (umask 077 → mode 0600) so other local users on the server can't read it.
  ( umask 077
    cat > .env <<EOF
# Generated by start.sh — SuperStatus reachable on the LAN by IP.
# Plain HTTP on the LAN. For internet exposure use a TLS proxy (docs/self-hosting.md).
BIND_ADDR=0.0.0.0
WEB_PORT=${WEB_PORT}
IDENTITY_PORT=${IDENTITY_PORT}
# #358: no WEBAPP_HTTP / IDP_PUBLIC_HTTP — the login redirect follows the host the
# browser uses (the issuer is pinned to the internal authority). Pin your public
# address in the console after first run (Settings → Access & security) to harden it.
IDP_HTTP=http://identity:8080
POSTGRES_PASSWORD=$(gen_secret)
OIDC_WEB_CLIENT_SECRET=$(gen_secret)
EOF
  )
  chmod 600 .env 2>/dev/null || true   # belt-and-suspenders if umask was overridden
else
  echo "Using existing .env (delete it to regenerate)."
fi

echo "Building and starting (first run takes a few minutes) ..."
docker compose up -d --build

cat <<EOF

SuperStatus is starting. From any machine on your network, open:

    http://${HOST_IP}:${WEB_PORT}

...or any other address this host answers at — the login adapts to it. Make sure
BOTH the web port (${WEB_PORT}) and the identity port (${IDENTITY_PORT}) are reachable
from your browser (open them in your firewall / cloud NSG).

The first visit creates your administrator account. Then pin your public
address in the console (Settings → Access & security) to harden sign-in.
Logs:  docker compose logs -f      Stop:  docker compose down
EOF
