#!/usr/bin/env bash
#
# Start SuperStatus on this machine and make it reachable by IP on your LAN.
#
#   ./start.sh
#
# Auto-detects this host's IP, writes a .env with generated secrets, and brings
# the stack up. Then open http://<this-host-ip>:8080 from any machine on your
# network and create your admin account.
#
# Overrides:  HOST_IP=10.0.0.5 WEB_PORT=8080 IDENTITY_PORT=8081 ./start.sh
#
# This serves plain HTTP on your LAN — fine for a trusted network. To expose it
# on the internet, put it behind a TLS reverse proxy instead (docs/self-hosting.md).
set -euo pipefail
cd "$(dirname "$0")"

WEB_PORT="${WEB_PORT:-8080}"
IDENTITY_PORT="${IDENTITY_PORT:-8081}"

# True for RFC-1918 / loopback / link-local addresses — i.e. an address very
# likely NOT how a browser on another network reaches this host. A cloud VM sees
# only its private NIC via `hostname -I`, so the auto-detected IP would bake an
# unreachable OIDC issuer into .env (the login redirect to ${HOST_IP} times out).
is_private_ip() {
  case "$1" in
    localhost|127.*|169.254.*) return 0 ;;
    10.*|192.168.*) return 0 ;;
    172.1[6-9].*|172.2[0-9].*|172.3[0-1].*) return 0 ;;
    *) return 1 ;;
  esac
}

# Prompt on the controlling terminal for the advertised host, echoing the typed
# value on stdout. Returns non-zero when there is no usable terminal (callers
# fall back to the detected value). Probe ( : > /dev/tty ) for an *openable*
# terminal rather than `[ -r /dev/tty ]`: the 0666 device node passes the
# read-bit test from cron/systemd/CI where opening it ENXIOs. Invoked in an `if`
# condition so set -e can't abort the script.
prompt_host() {
  ( : > /dev/tty ) 2>/dev/null || return 1
  printf 'Advertised host (IP or hostname) for browser access [%s]: ' "$1" > /dev/tty
  read -r _reply < /dev/tty || _reply=""
  printf '%s' "$_reply"
}

# The chosen HOST_IP is baked into the OIDC issuer (WEBAPP_HTTP / IDP_PUBLIC_HTTP),
# so it must be browser-reachable, not just a private NIC address. Override
# non-interactively with HOST_IP=<ip-or-hostname>.
HOST_IP="${HOST_IP:-}"
HOST_IP_FROM_ENV=true
if [ -z "$HOST_IP" ]; then
  HOST_IP_FROM_ENV=false
  HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
if [ -z "$HOST_IP" ]; then
  echo "Could not detect this host's IP. Re-run with: HOST_IP=<your-server-ip> ./start.sh" >&2
  exit 1
fi

# On a fresh install where the operator did not pass HOST_IP, let them confirm or
# correct the advertised host. Skipped when HOST_IP was set explicitly or when an
# existing .env is being reused, so established LAN / automation paths see no prompt.
if [ "$HOST_IP_FROM_ENV" = "false" ] && [ ! -f .env ]; then
  if is_private_ip "$HOST_IP"; then
    echo ""
    echo "Detected a private/LAN address for this host: ${HOST_IP}"
    echo "This address is written into the login (OIDC) issuer. If you reach"
    echo "SuperStatus from another network — a cloud VM's public IP, or a"
    echo "hostname — enter that below, or sign-in will redirect to ${HOST_IP}"
    echo "and fail."
  fi
  if _host=$(prompt_host "$HOST_IP"); then
    [ -n "$_host" ] && HOST_IP="$_host"
  elif is_private_ip "$HOST_IP"; then
    echo "Non-interactive — keeping ${HOST_IP}. If that is not reachable from your"
    echo "browser, re-run with: HOST_IP=<public-ip-or-hostname> ./start.sh"
  fi
fi

gen_secret() { openssl rand -base64 24 2>/dev/null || head -c 18 /dev/urandom | base64; }

if [ ! -f .env ]; then
  echo "Writing .env for LAN access on ${HOST_IP} ..."
  # .env holds POSTGRES_PASSWORD / OIDC_WEB_CLIENT_SECRET — create it owner-only
  # (umask 077 → mode 0600) so other local users on the server can't read it.
  ( umask 077
    cat > .env <<EOF
# Generated by start.sh — SuperStatus reachable on the LAN by IP.
# Plain HTTP on the LAN. For internet exposure use a TLS proxy (docs/self-hosting.md).
BIND_ADDR=0.0.0.0
WEB_PORT=${WEB_PORT}
IDENTITY_PORT=${IDENTITY_PORT}
WEBAPP_HTTP=http://${HOST_IP}:${WEB_PORT}
IDP_PUBLIC_HTTP=http://${HOST_IP}:${IDENTITY_PORT}
IDP_HTTP=http://identity:8080
POSTGRES_PASSWORD=$(gen_secret)
OIDC_WEB_CLIENT_SECRET=$(gen_secret)
EOF
  )
  chmod 600 .env 2>/dev/null || true   # belt-and-suspenders if umask was overridden
else
  echo "Using existing .env (delete it to regenerate)."
fi

echo "Building and starting (first run takes a few minutes) ..."
docker compose up -d --build

cat <<EOF

SuperStatus is starting. From any machine on your network, open:

    http://${HOST_IP}:${WEB_PORT}

The first visit creates your administrator account.
Logs:  docker compose logs -f      Stop:  docker compose down
EOF
