// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperStatus.Data.Repositories;

#nullable disable

namespace SuperStatus.ApiService.Migrations
{
    [DbContext(typeof(SuperStatusContext))]
    [Migration("20241208151921_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HistoricalStatusDataId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeOfExecutionUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalStatusDataId")
                        .IsUnique();

                    b.ToTable("HistoricalStatusActionSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CheckFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResponseTimeInMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeOfCheckUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoricalStatusDataSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.HistoricalStatusData", "HistoricalStatusData")
                        .WithOne("HistoricalStatusAction")
                        .HasForeignKey("SuperStatus.Data.Entities.HistoricalStatusAction", "HistoricalStatusDataId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("HistoricalStatusData");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Navigation("HistoricalStatusAction");
                });
#pragma warning restore 612, 618
        }
    }
}
