// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperStatus.Data.DatabaseContext;

#nullable disable

namespace SuperStatus.Data.Migrations.SuperStatusDbMigration
{
    [DbContext(typeof(SuperStatusDb))]
    [Migration("20250817105403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<long>("HistoricalStatusDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeOfExecutionUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalStatusDataId")
                        .IsUnique();

                    b.ToTable("HistoricalStatusActionSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CheckFailed")
                        .HasColumnType("boolean");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<long>("ResponseTimeInMs")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeOfCheckUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HistoricalStatusDataSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.StatusCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("ExpectedResponseTimeInMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWebHookOnErrorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusCheckUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThrottleWebHookToExecuteOnlyEveryXMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebHookOnErrorUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusCheckSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.HistoricalStatusData", "HistoricalStatusData")
                        .WithOne("HistoricalStatusAction")
                        .HasForeignKey("SuperStatus.Data.Entities.HistoricalStatusAction", "HistoricalStatusDataId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("HistoricalStatusData");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Navigation("HistoricalStatusAction");
                });
#pragma warning restore 612, 618
        }
    }
}
