// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperStatus.Data.DatabaseContext;

#nullable disable

namespace SuperStatus.Data.Migrations.SuperStatusDbMigration
{
    [DbContext(typeof(SuperStatusDb))]
    [Migration("20260528200628_AddWebhookExecutionLog")]
    partial class AddWebhookExecutionLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<long>("HistoricalStatusDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeOfExecutionUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalStatusDataId")
                        .IsUnique();

                    b.ToTable("HistoricalStatusActionSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CheckFailed")
                        .HasColumnType("boolean");

                    b.Property<int>("FailType")
                        .HasColumnType("integer");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<long?>("IncidentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponseTimeInMs")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeOfCheckUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("TimeOfCheckUTC")
                        .HasDatabaseName("IX_HistoricalStatusDataSet_TimeOfCheckUTC");

                    b.HasIndex("StatusCheckId", "TimeOfCheckUTC")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HistoricalStatusDataSet_StatusCheckId_TimeOfCheckUTC");

                    b.ToTable("HistoricalStatusDataSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AuotmaticallyGeneratedReport")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VisibleToPublic")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("IncidentSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.StatusCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("ExpectedResponseTimeInMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWebHookOnErrorEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusCheckUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThrottleWebHookToExecuteOnlyEveryXMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebHookOnErrorUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusCheckSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.WebhookExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttemptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long?>("HistoricalStatusDataId")
                        .HasColumnType("bigint");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_WebhookExecutionLogSet_AttemptedUtc");

                    b.HasIndex("HistoricalStatusDataId");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("IX_WebhookExecutionLogSet_Outcome");

                    b.HasIndex("StatusCheckId", "AttemptedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_WebhookExecutionLogSet_StatusCheckId_AttemptedUtc");

                    b.ToTable("WebhookExecutionLogSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.HistoricalStatusData", "HistoricalStatusData")
                        .WithOne("HistoricalStatusAction")
                        .HasForeignKey("SuperStatus.Data.Entities.HistoricalStatusAction", "HistoricalStatusDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalStatusData");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.Incident", null)
                        .WithMany("HistoricalStatusData")
                        .HasForeignKey("IncidentId");

                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusCheck");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.WebhookExecutionLog", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.HistoricalStatusData", "HistoricalStatusData")
                        .WithMany()
                        .HasForeignKey("HistoricalStatusDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalStatusData");

                    b.Navigation("StatusCheck");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Navigation("HistoricalStatusAction");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.Incident", b =>
                {
                    b.Navigation("HistoricalStatusData");
                });
#pragma warning restore 612, 618
        }
    }
}
