// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperStatus.Data.DatabaseContext;

#nullable disable

namespace SuperStatus.Data.Migrations.SuperStatusDbMigration
{
    [DbContext(typeof(SuperStatusDb))]
    [Migration("20260612092001_LinkedWebhooksAndAlertProfiles")]
    partial class LinkedWebhooksAndAlertProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperStatus.Data.Entities.AlertDeliveryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlertProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AttemptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertProfileId");

                    b.HasIndex("AttemptedUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_AlertDeliveryLogSet_AttemptedUtc");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("IX_AlertDeliveryLogSet_Outcome");

                    b.HasIndex("StatusCheckId", "AttemptedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AlertDeliveryLogSet_StatusCheckId_AttemptedUtc");

                    b.ToTable("AlertDeliveryLogSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.AlertProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailRecipients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UsesSiteDefaultRecipients")
                        .HasColumnType("boolean");

                    b.Property<bool>("WebPushEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AlertProfileSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.BackfillReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BackfillReportSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.DailyStatusRollup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Degraded")
                        .HasColumnType("integer");

                    b.Property<int>("Down")
                        .HasColumnType("integer");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<int>("Unreachable")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusCheckId", "Day")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyStatusRollupSet_StatusCheckId_Day");

                    b.ToTable("DailyStatusRollupSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<long>("HistoricalStatusDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeOfExecutionUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalStatusDataId")
                        .IsUnique();

                    b.ToTable("HistoricalStatusActionSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CheckFailed")
                        .HasColumnType("boolean");

                    b.Property<int>("FailType")
                        .HasColumnType("integer");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<long?>("IncidentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponseTimeInMs")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeOfCheckUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("TimeOfCheckUTC")
                        .HasDatabaseName("IX_HistoricalStatusDataSet_TimeOfCheckUTC");

                    b.HasIndex("StatusCheckId", "TimeOfCheckUTC")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HistoricalStatusDataSet_StatusCheckId_TimeOfCheckUTC");

                    b.ToTable("HistoricalStatusDataSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AuotmaticallyGeneratedReport")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<long?>("SourceStatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VisibleToPublic")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SourceStatusCheckId")
                        .IsUnique()
                        .HasDatabaseName("IX_IncidentSet_SourceStatusCheckId_OpenAuto")
                        .HasFilter("\"SourceStatusCheckId\" IS NOT NULL AND NOT \"Resolved\" AND \"AuotmaticallyGeneratedReport\"");

                    b.ToTable("IncidentSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.PushSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastNotifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("IX_PushSubscriptionSet_Endpoint");

                    b.ToTable("PushSubscriptionSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.RollupMaintenanceState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BackfillVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RollupMaintenanceStateSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.SiteSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AiEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiPromptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AiTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("AlertDefaultRecipients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutoIncidentThresholdMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FooterLinksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OnboardedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ShowAdminLink")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpFromAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmtpFromName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<bool>("SmtpUseStartTls")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SmtpVerifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UpdateCheckEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("UpdateLastCheckError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateLastCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdateLatestNotesUrl")
                        .HasColumnType("text");

                    b.Property<string>("UpdateLatestVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VapidPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VapidPublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteSettingsSet", t =>
                        {
                            t.HasCheckConstraint("CK_SiteSettingsSet_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.StatusCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AlertLastFiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AlertOnFailureThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("AlertOnOutageMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("AlertOnRecovery")
                        .HasColumnType("boolean");

                    b.Property<int>("AlertThrottleMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AlertedOutageDownSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AutoIncidentEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DownSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailAlertsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailRecipients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("ExpectedResponseTimeInMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWebHookOnErrorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusCheckUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThrottleWebHookToExecuteOnlyEveryXMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebHookOnErrorUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WebPushAlertsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("StatusCheckSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.StatusCheckAlertProfile", b =>
                {
                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<long>("AlertProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AlertLastFiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AlertedOutageDownSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StatusCheckId", "AlertProfileId");

                    b.HasIndex("AlertProfileId");

                    b.ToTable("StatusCheckAlertProfileSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.StatusCheckWebhook", b =>
                {
                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<long>("WebhookId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastFiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StatusCheckId", "WebhookId");

                    b.HasIndex("WebhookId");

                    b.ToTable("StatusCheckWebhookSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.Webhook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThrottleMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WebhookSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.WebhookExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttemptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long?>("HistoricalStatusDataId")
                        .HasColumnType("bigint");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<long>("StatusCheckId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("WebhookId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_WebhookExecutionLogSet_AttemptedUtc");

                    b.HasIndex("HistoricalStatusDataId");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("IX_WebhookExecutionLogSet_Outcome");

                    b.HasIndex("WebhookId");

                    b.HasIndex("StatusCheckId", "AttemptedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_WebhookExecutionLogSet_StatusCheckId_AttemptedUtc");

                    b.ToTable("WebhookExecutionLogSet");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.AlertDeliveryLog", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.AlertProfile", "AlertProfile")
                        .WithMany()
                        .HasForeignKey("AlertProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertProfile");

                    b.Navigation("StatusCheck");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.DailyStatusRollup", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusCheck");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusAction", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.HistoricalStatusData", "HistoricalStatusData")
                        .WithOne("HistoricalStatusAction")
                        .HasForeignKey("SuperStatus.Data.Entities.HistoricalStatusAction", "HistoricalStatusDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalStatusData");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.Incident", null)
                        .WithMany("HistoricalStatusData")
                        .HasForeignKey("IncidentId");

                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusCheck");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.StatusCheckAlertProfile", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.AlertProfile", "AlertProfile")
                        .WithMany()
                        .HasForeignKey("AlertProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertProfile");

                    b.Navigation("StatusCheck");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.StatusCheckWebhook", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperStatus.Data.Entities.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatusCheck");

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.WebhookExecutionLog", b =>
                {
                    b.HasOne("SuperStatus.Data.Entities.HistoricalStatusData", "HistoricalStatusData")
                        .WithMany()
                        .HasForeignKey("HistoricalStatusDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SuperStatus.Data.Entities.StatusCheck", "StatusCheck")
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperStatus.Data.Entities.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HistoricalStatusData");

                    b.Navigation("StatusCheck");

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.HistoricalStatusData", b =>
                {
                    b.Navigation("HistoricalStatusAction");
                });

            modelBuilder.Entity("SuperStatus.Data.Entities.Incident", b =>
                {
                    b.Navigation("HistoricalStatusData");
                });
#pragma warning restore 612, 618
        }
    }
}
